apiVersion: v1
kind: Service
metadata:
  name: hcmatrix-k8s-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/health"
spec:
  selector:
    app: hcmatrix-chatbot
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  externalTrafficPolicy: Local
