name: Integration Tests and Code Linting

on:
  push:
    branches:
      - master  # Trigger on pushes to master branch
  pull_request:
    types:
      - closed
    branches:
      - master  # Trigger when pull requests are merged into master

jobs:
  integration_tests:
    name: Run API Tests and Code Linting
    runs-on: ubuntu-latest  # Can change to macOS or Windows if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out the code

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use Python 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt  # Install from requirements.txt
          pip install chromadb==0.3.29 motor==3.7.0  # Install additional packages
          pip install --upgrade starlette==0.22.0 anyio

      - name: Run unit tests
        env:
          ADLS_CLIENT_SECRET: ${{ secrets.ADLS_CLIENT_SECRET }}
          SPEECH_SERVICE_KEY: ${{ secrets.SPEECH_SERVICE_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_EMBEDDING_API_KEY: ${{ secrets.AZURE_EMBEDDING_API_KEY }}
        run: pytest api_test.py  # Runs your unit test script

      - name: Run Flake8 for style checking
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  # Checks for critical issues
